#pragma once

void initializeData();
void displayMenu();
void listStudents();
void listCourses();
void listTeachers();
void listRecords();
void queryStudent();
void queryCourse();
void queryTeacher();
void queryRecord();
void addStudent();
void deleteStudent();
void updateStudent();
void deleteTeacher();
void updateTeacher();
void deleteCourse();
void updateCourse();